package com.example.bilingualbackend.db.enums;

public enum QuestionType {
    SELECT_ENGLISH_WORD,
    TYPE_WHAT_YOU_HEAR,
    DESCRIBE_IMAGE,
    LISTEN_AND_SELECT_ENGLISH_WORD,
    RECORD_SAYING_STATEMENT,
    RESPOND_N_WORDS,
    HIGHLIGHT_THE_ANSWER,
    SELECT_THE_MAIN_IDEA,
    SELECT_BEST_TITLE
}
